version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./:/mosquitto/:rw
      - ./config:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
